- name: Download calico operator yaml
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v{{ k8s_cni.version }}/manifests/tigera-operator.yaml
    dest: "{{ os_download_cache_dir }}/tigera-operator-v{{ k8s_cni.version }}.yaml"
    mode: "0440"

- name: Download calico custom resources
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/projectcalico/calico/v{{ k8s_cni.version }}/manifests/custom-resources.yaml
    dest: "{{ os_download_cache_dir }}/tigera-calico-custom-resources-v{{ k8s_cni.version }}.yaml"
    mode: "0440"

- name: Replace cidr in custom resources
  ansible.builtin.command:
    cmd: "sed -Ei 's@(.*)cidr(.*)@\\1cidr: {{ k8s_cluster_cidr }}@g' '{{ os_download_cache_dir }}/tigera-calico-custom-resources-v{{ k8s_cni.version }}.yaml'"

- name: Install calico operator
  ansible.builtin.shell:
    cmd: KUBECONFIG=/etc/kubernetes/admin.conf kubectl create -f {{ os_download_cache_dir }}/tigera-operator-v{{ k8s_cni.version }}.yaml

- name: Install calico custom resources
  ansible.builtin.shell:
    cmd: KUBECONFIG=/etc/kubernetes/admin.conf kubectl create -f {{ os_download_cache_dir }}/tigera-calico-custom-resources-v{{ k8s_cni.version }}.yaml

- name: Download calicoctl
  ansible.builtin.get_url:
    url: https://github.com/projectcalico/calico/releases/download/v{{ k8s_cni.cli_version }}/calicoctl-linux-amd64
    dest: /usr/local/bin/calicoctl
    mode: "0755"
