- name: Check if cluster already exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_conf

- name: Copy kubadm-conf
  ansible.builtin.template:
    src: kubeadm-conf.yaml.j2
    dest: "{{ k8s_kubeadm_conf }}"
    mode: "0644"
  when: not k8s_admin_conf.stat.exists

- name: Kubeadm init
  ansible.builtin.command: kubeadm init --config /tmp/kubeadm-conf.yaml --upload-certs
  register: kubeadm_init_output
  when: not k8s_admin_conf.stat.exists

- name: Show output
  ansible.builtin.copy:
    content: "{{ kubeadm_init_output }}"
    dest: ~/kubeadm_init.output
