- name: Check if cluster already exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_conf

- name: Copy kubadm-conf
  ansible.builtin.template:
    src: kubeadm-conf.yaml.j2
    dest: "{{ k8s_kubeadm_conf }}"
    mode: "0644"
  when: not k8s_admin_conf.stat.exists

- name: Set disable kube-proxy fact for calico
  set_fact:
    k8s_disable_kube_proxy: "{{ '--skip-phases=addon/kube-proxy' if k8s_cni.name == 'calico' else '' }}"
  when: not k8s_admin_conf.stat.exists

- name: Kubeadm init
  ansible.builtin.command: kubeadm init --upload-certs {{ k8s_disable_kube_proxy }} --config "{{ k8s_kubeadm_conf }}"
  register: kubeadm_init_output
  when: not k8s_admin_conf.stat.exists

- name: Save kubeadm output
  ansible.builtin.copy:
    content: "{{ kubeadm_init_output }}"
    dest: ~/kubeadm_init.output
  when: not k8s_admin_conf.stat.exists
