- name: Copy root CA crt to etcd pki dir
  ansible.builtin.copy:
    dest: "{{ k8s_ca_crt_file }}"
    content: "{{ k8s_root_ca_crt }}"
    mode: "0644"

- name: Copy root CA key to etcd pki dir
  ansible.builtin.copy:
    dest: "{{ k8s_ca_key_file }}"
    content: "{{ k8s_root_ca_key }}"
    mode: "0600"
