- name: Set distro fact
  ansible.builtin.set_fact:
    os_distro: "{{ ansible_distribution | lower }}"

- name: Set distro fact
  ansible.builtin.set_fact:
    os_download_cache_dir: "{{ os_default_download_chache_dir }}"
  when: os_download_cache_dir is undefined
