- name: Set distro fact
  ansible.builtin.set_fact:
    os_distro: "{{ ansible_distribution | lower }}"

- name: Set distro fact
  ansible.builtin.set_fact:
    os_download_cache_dir: "{{ os_default_download_chache_dir }}"
  when: os_download_cache_dir is undefined

- name: Add root cert to trust store of the OS
  ansible.builtin.include_tasks: "{{ os_distro }}_truststore.yml"

- name: Prepare OS
  ansible.builtin.include_tasks: "{{ os_distro }}_prepare.yml"

- name: Apply sysctl settings
  ansible.builtin.include_tasks: sysctl.yml
