- name: OS update cache
  ansible.builtin.apt:
    update_cache: true

- name: OS upgrade
  ansible.builtin.apt:
    upgrade: dist
  when: os_upgrade

- name: Check if reboot is needed
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: check_reboot

- name: Reboot if needed
  ansible.builtin.reboot:
    msg: "Rebooting due to /var/run/reboot-required"
    post_reboot_delay: 10
    reboot_timeout: 600
  when: check_reboot.stat.exists

- name: Install required OS packages
  ansible.builtin.apt:
    update_cache: true
    name: "{{ os_required_packages }}"
    state: present

- name: Ensure download cache directory
  ansible.builtin.file:
    name: "{{ os_download_cache_dir }}"
    state: directory
    mode: "0755"
