- name: Check if cluster already exists
  stat:
    path: /etc/kubernetes/admin.conf
  register: k8s_admin_conf
  when: ansible_hostname == groups['k8s_cp'][0]

- name: Copy kubadm-conf
  ansible.builtin.template:
    src: kubeadm-conf.yaml.j2
    dest: /tmp/kubeadm-conf.yaml
    mode: "0644"
  when: ansible_hostname == groups['k8s_cp'][0] and not k8s_admin_conf.stat.exists

- name: Kubeadm init
  ansible.builtin.command: kubeadm init --config /tmp/kubeadm-conf.yaml --upload-certs
  register: kubeadm_init_output
  run_once: true
  when: ansible_hostname == groups['k8s_cp'][0] and not k8s_admin_conf.stat.exists
