- name: Install haproxy package
  ansible.builtin.package:
    name: haproxy

- name: Copy haproxy.conf
  ansible.builtin.template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_conf_file }}"
  notify: Restart haproxy
