- name: Set base print join command
  set_fact:
    k8s_join_print_command: kubeadm token create --print-join-command

- name: Get certificate key from first cp node if control plane
  ansible.builtin.command:
    cmd: kubeadm init phase upload-certs --upload-certs --config "{{ k8s_kubeadm_conf }}"
  register: k8s_join_cert_key_output
  delegate_to: "{{ groups['k8s_cp'][0] }}"
  when: k8s_join_control_plane

- name: Set certificate key if control plane
  set_fact:
    k8s_join_cp_cert_key: "{{ k8s_join_cert_key_output.stdout_lines[-1] }}"
  when: k8s_join_control_plane

- name: Add certificate key to print command if control plane
  set_fact:
    k8s_join_print_command: "{{ k8s_join_print_command }} --certificate-key {{ k8s_join_cp_cert_key }}"
  when: k8s_join_control_plane

- name: Get join command from first cp node
  ansible.builtin.command:
    cmd: "{{ k8s_join_print_command }}"
  register: k8s_join_command
  delegate_to: "{{ groups['k8s_cp'][0] }}"

- name: Execute join command
  ansible.builtin.command:
    cmd: "{{ k8s_join_command.stdout }}"
