- name: Set base print join command
  set_fact:
    k8s_join_print_command: kubeadm token create --print-join-command

- name: Control plane join
  ansible.builtin.include_tasks: join_control_plane.yml
  when: k8s_join_control_plane

- name: Worker join
  ansible.builtin.include_tasks: join_worker.yml
  when: not k8s_join_control_plane

- name: Get join command from first cp node
  ansible.builtin.command:
    cmd: "{{ k8s_join_print_command }}"
  register: k8s_join_command
  delegate_to: "{{ groups['k8s_cp'][0] }}"
  when: not joined_already

- name: Execute join command
  ansible.builtin.command:
    cmd: "{{ k8s_join_command.stdout }}"
  when: not joined_already
