- name: Configure kubelet
  ansible.builtin.include_tasks: kubelet.yml

- name: Copy root ca crt and key
  ansible.builtin.include_tasks: root_ca.yml

- name: Configure kubeadm, certs and etcd
  ansible.builtin.include_tasks: kubeadm.yml
