k8s_version: "1.32"
k8s_container_runtime:
  name: crio
  version: "1.30"
  package: cri-o
  endpoint: "unix:///var/run/crio/crio.sock"

sysctl_settings:
  net.ipv4.ip_forward: 1

k8s_packages:
  - kubeadm
  - kubelet
  - kubectl

k8s_static_pod_manifest_dir: /etc/kubernetes/manifests

kube_apiserver: "kube-apiserver.dev.tuftuf.org"
kube_apiserver_port: "6443"

k8s_cni:
  name: cilium
  version: 1.16.6
  cli_version: v0.16.23
  cli_arch: amd64
