- name: Disable swap
  ansible.builtin.command: swapoff -a
  changed_when: false

- name: Apply sysctl settings
  ansible.posix.sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    sysctl_set: true
    state: present
  loop: "{{ k8s_sysctl_settings | dict2items }}"

- name: Modprobe br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present
