- name: Configure OS
  ansible.builtin.include_tasks: common_os_configuration.yml

- name: Add kubernetes repo
  ansible.builtin.include_tasks: "{{ os_distro }}_prepare.yml"

- name: Install crio
  ansible.builtin.include_tasks: "{{ os_distro }}_{{ k8s_container_runtime }}.yml"
