- name: Configure OS
  ansible.builtin.include_tasks: common_os_configuration.yml

- name: Add kubernetes repo
  ansible.builtin.include_tasks: "{{ os_distro }}_k8s.yml"

- name: Pin versions
  ansible.builtin.include_tasks: "{{ os_distro }}_pin.yml"

- name: Install and configure {{ k8s_container_runtime.name }}
  ansible.builtin.include_tasks: "{{ os_distro }}_{{ k8s_container_runtime.name }}.yml"
