- name: Configure OS
  ansible.builtin.include_tasks: common_os_configuration.yml

- name: Add kubernetes repo
  ansible.builtin.include_tasks: "{{ os_distro }}_prepare.yml"

- name: Configure repo for {{ k8s_container_runtime.name }}
  ansible.builtin.include_tasks: "{{ os_distro }}_{{ k8s_container_runtime.name }}.yml"

- name: Install k8s packages
  ansible.builtin.include_tasks: install_packages.yml
